"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, PlayCircle, Rocket, Sparkles } from "lucide-react";

import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { settingsClientService } from "@/services/settings-client-service";
import type { OnboardingChecklist, OnboardingRecommendationResult, OnboardingRun, TemplateFitRecommendation } from "@/types/productization";

interface OnboardingState {
  role: string;
  checklist: OnboardingChecklist;
  currentTemplate: {
    templateKey: string;
    displayName: string;
  } | null;
  recommendation: OnboardingRecommendationResult;
  recommendationUsedFallback: boolean;
  recommendationFallbackReason: string | null;
  latestRuns: OnboardingRun[];
  featureFlags: Record<string, boolean>;
  entitlement: {
    planTier: string;
    status: string;
  };
}

export default function OnboardingSettingsPage(): JSX.Element {
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [state, setState] = useState<OnboardingState | null>(null);
  const [templateFit, setTemplateFit] = useState<{
    recommendation: TemplateFitRecommendation;
    usedFallback: boolean;
    fallbackReason: string | null;
  } | null>(null);

  const canRunAdminTools = useMemo(() => state?.role === "owner" || state?.role === "admin", [state]);

  async function load(): Promise<void> {
    try {
      setLoading(true);
      setError(null);
      const payload = await settingsClientService.getOnboardingSettings();
      setState({
        role: payload.role,
        checklist: payload.checklist,
        currentTemplate: payload.currentTemplate,
        recommendation: payload.recommendation,
        recommendationUsedFallback: payload.recommendationUsedFallback,
        recommendationFallbackReason: payload.recommendationFallbackReason,
        latestRuns: payload.latestRuns,
        featureFlags: payload.featureFlags,
        entitlement: {
          planTier: payload.entitlement.planTier,
          status: payload.entitlement.status
        }
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load onboarding data");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
  }, []);

  async function runFlow(runType: "first_time_setup" | "trial_bootstrap" | "demo_seed" | "reinitialize_demo"): Promise<void> {
    setRunning(true);
    setMessage(null);
    setError(null);

    try {
      const payload = await settingsClientService.runOnboarding({ runType });
      setMessage(payload.message);
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to run onboarding flow");
    } finally {
      setRunning(false);
    }
  }

  async function runTemplateRecommend(): Promise<void> {
    setRunning(true);
    setMessage(null);
    setError(null);
    try {
      const payload = await settingsClientService.recommendTemplate();
      setTemplateFit(payload);
      setMessage(
        payload.usedFallback
          ? `Template recommendation generated by fallback: ${payload.fallbackReason ?? "unknown"}`
          : "Template recommendation generated."
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to recommend template");
    } finally {
      setRunning(false);
    }
  }

  if (loading || !state) {
    return <div className="text-sm text-muted-foreground">Loading onboarding center...</div>;
  }

  return (
    <div>
      <PageHeader
        title="Onboarding & Demo"
        description="Guide new organizations from setup to first value with checklist, demo seed and trial bootstrap flows."
        action={
          <Button variant="outline" onClick={() => void load()} disabled={loading || running}>
            Refresh
          </Button>
        }
      />

      {error ? <p className="mb-4 text-sm text-red-600">{error}</p> : null}
      {message ? <p className="mb-4 text-sm text-emerald-700">{message}</p> : null}

      <div className="grid gap-4 xl:grid-cols-3">
        <Card className="xl:col-span-2">
          <CardHeader>
            <CardTitle>Onboarding Checklist</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <p className="text-sm text-muted-foreground">
              Progress {state.checklist.progress}% ({state.checklist.completedCount}/{state.checklist.totalCount})
            </p>
            {state.checklist.items.map((item) => (
              <div key={item.key} className="flex items-start gap-2 rounded-md border border-slate-200 p-2">
                <CheckCircle2 className={`mt-0.5 h-4 w-4 ${item.completed ? "text-emerald-600" : "text-slate-300"}`} />
                <div>
                  <p className="text-sm font-medium text-slate-900">{item.title}</p>
                  <p className="text-xs text-muted-foreground">{item.detail}</p>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Run Setup Tools</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <p className="text-xs text-muted-foreground">
              role={state.role} | plan={state.entitlement.planTier}/{state.entitlement.status}
            </p>
            <Button className="w-full" disabled={!canRunAdminTools || running} onClick={() => void runFlow("first_time_setup")}>
              <PlayCircle className="mr-2 h-4 w-4" />
              Run First Time Setup
            </Button>
            <Button className="w-full" variant="outline" disabled={!canRunAdminTools || running} onClick={() => void runFlow("trial_bootstrap")}>
              <Rocket className="mr-2 h-4 w-4" />
              Run Trial Bootstrap
            </Button>
            <Button
              className="w-full"
              variant="secondary"
              disabled={!canRunAdminTools || running || !state.featureFlags.demo_seed_tools}
              onClick={() => void runFlow("demo_seed")}
            >
              Demo Seed
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link href="/imports">Open Import Center</Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link href="/settings/templates">Open Template Center</Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link href="/growth">Open Growth Workspace</Link>
            </Button>
            <Button asChild className="w-full" variant="outline">
              <Link href="/manager/conversion">Open Conversion View</Link>
            </Button>
            <Button className="w-full" variant="outline" onClick={() => void runTemplateRecommend()} disabled={running}>
              Recommend Industry Template
            </Button>
            {!state.featureFlags.demo_seed_tools ? <p className="text-xs text-muted-foreground">Demo seed is disabled by feature flags.</p> : null}
            {!canRunAdminTools ? <p className="text-xs text-muted-foreground">Only owner/admin can run onboarding tools.</p> : null}
          </CardContent>
        </Card>

        <Card className="xl:col-span-3">
          <CardHeader>
            <CardTitle>Industry Template</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            {state.currentTemplate ? (
              <>
                <p>
                  Current template:{" "}
                  <Badge variant="secondary">
                    {state.currentTemplate.displayName} ({state.currentTemplate.templateKey})
                  </Badge>
                </p>
                <p className="text-muted-foreground">
                  You can preview diff before apply, then choose additive / merge / override mode.
                </p>
              </>
            ) : (
              <p className="text-muted-foreground">No industry template is active yet. Select one in template center.</p>
            )}
          </CardContent>
        </Card>

        {templateFit ? (
          <Card className="xl:col-span-3">
            <CardHeader>
              <CardTitle>Template Fit Result</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <p>
                recommended: <Badge variant="secondary">{templateFit.recommendation.recommendedTemplateKey}</Badge>
              </p>
              <p>apply mode: {templateFit.recommendation.recommendedApplyMode}</p>
              <p>fit reasons: {templateFit.recommendation.fitReasons.join(" / ") || "-"}</p>
              <p>mismatch risks: {templateFit.recommendation.risksOfMismatch.join(" / ") || "-"}</p>
              <p>overrides: {templateFit.recommendation.recommendedOverrides.join(" / ") || "-"}</p>
            </CardContent>
          </Card>
        ) : null}

        <Card className="xl:col-span-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-sky-700" />
              Onboarding Recommendation
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <p>
              <strong>Next setup steps:</strong> {state.recommendation.nextBestSetupSteps.join(" / ") || "-"}
            </p>
            <p>
              <strong>Missing foundations:</strong> {state.recommendation.missingFoundations.join(" / ") || "-"}
            </p>
            <p>
              <strong>Recommended demo flow:</strong> {state.recommendation.recommendedDemoFlow.join(" / ") || "-"}
            </p>
            <p>
              <strong>Team actions:</strong> {state.recommendation.recommendedTeamActions.join(" / ") || "-"}
            </p>
            <p>
              <strong>Risks if skipped:</strong> {state.recommendation.risksIfSkipped.join(" / ") || "-"}
            </p>
            {state.recommendationUsedFallback ? (
              <p className="text-xs text-amber-700">Fallback recommendation used: {state.recommendationFallbackReason ?? "unknown"}</p>
            ) : (
              <Badge>AI recommendation</Badge>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent Runs</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            {state.latestRuns.length === 0 ? <p className="text-muted-foreground">No onboarding runs yet.</p> : null}
            {state.latestRuns.map((run) => (
              <div key={run.id} className="rounded-md border border-slate-200 p-2">
                <p className="font-medium text-slate-900">{run.runType}</p>
                <p className="text-xs text-muted-foreground">status={run.status} · {run.createdAt.slice(0, 10)}</p>
                <p className="mt-1 text-xs text-muted-foreground">{run.summary}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}




