import type { ActionOutcomeCaptureAssistResult } from "@/types/ai";

export function buildFallbackOutcomeAssist(params: {
  preferredOutcomeType: ActionOutcomeCaptureAssistResult["outcome_type"];
  previousStage?: string | null;
  nextStage?: string | null;
  summaryHint?: string | null;
  usedPrepCard?: boolean;
  usedDraft?: boolean;
}): ActionOutcomeCaptureAssistResult {
  const stageChanged = Boolean(params.previousStage && params.nextStage && params.previousStage !== params.nextStage);
  return {
    outcome_type: params.preferredOutcomeType,
    result_status: stageChanged ? "positive_progress" : "neutral",
    stage_changed: stageChanged,
    old_stage: params.previousStage ?? null,
    new_stage: params.nextStage ?? null,
    customer_sentiment_shift: "unknown",
    key_outcome_summary: params.summaryHint ?? "Action completed. Please confirm whether customer progress moved forward.",
    new_objections: [],
    new_risks: [],
    next_step_defined: false,
    next_step_text: null,
    followup_due_at: null,
    used_prep_card: params.usedPrepCard ?? false,
    used_draft: params.usedDraft ?? false,
    usefulness_rating: "unknown",
    notes: "Fallback outcome draft generated by rule template."
  };
}
