"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { settingsClientService } from "@/services/settings-client-service";
import type {
  IndustryTemplate,
  IndustryTemplateContext,
  TemplateApplicationSummary,
  TemplateApplyMode,
  TemplateApplyStrategy,
  TemplateFitRecommendation
} from "@/types/productization";

interface TemplateCenterState {
  role: string;
  templates: IndustryTemplate[];
  currentTemplate: IndustryTemplate | null;
  currentAssignment: IndustryTemplateContext["assignment"];
}

const APPLY_MODES: TemplateApplyMode[] = ["onboarding_default", "manual_apply", "demo_seed", "trial_bootstrap"];
const APPLY_STRATEGIES: TemplateApplyStrategy[] = ["additive_only", "merge_prefer_existing", "template_override_existing"];

export default function TemplateSettingsPage(): JSX.Element {
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const [state, setState] = useState<TemplateCenterState | null>(null);
  const [selectedTemplateIdOrKey, setSelectedTemplateIdOrKey] = useState<string>("");
  const [templateDetail, setTemplateDetail] = useState<Awaited<ReturnType<typeof settingsClientService.getTemplateDetail>> | null>(null);
  const [recommendation, setRecommendation] = useState<{
    recommendation: TemplateFitRecommendation;
    usedFallback: boolean;
    fallbackReason: string | null;
  } | null>(null);
  const [preview, setPreview] = useState<{
    diff: {
      changedKeys: string[];
      unchangedKeys: string[];
      notes: string[];
    };
    summary: TemplateApplicationSummary;
    summaryUsedFallback: boolean;
    summaryFallbackReason: string | null;
  } | null>(null);

  const [applyMode, setApplyMode] = useState<TemplateApplyMode>("manual_apply");
  const [applyStrategy, setApplyStrategy] = useState<TemplateApplyStrategy>("merge_prefer_existing");
  const [generateDemoSeed, setGenerateDemoSeed] = useState(false);

  const canWrite = useMemo(
    () => state?.role === "owner" || state?.role === "admin",
    [state]
  );

  const load = async (): Promise<void> => {
    try {
      setLoading(true);
      setError(null);
      const payload = await settingsClientService.getTemplateCenter();
      setState(payload);

      const selected = selectedTemplateIdOrKey || payload.currentTemplate?.id || payload.templates[0]?.id || "";
      setSelectedTemplateIdOrKey(selected);
      if (selected) {
        const detail = await settingsClientService.getTemplateDetail(selected);
        setTemplateDetail(detail);
      } else {
        setTemplateDetail(null);
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Failed to load template center");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const loadDetail = async (templateIdOrKey: string): Promise<void> => {
    setSelectedTemplateIdOrKey(templateIdOrKey);
    setPreview(null);
    try {
      const detail = await settingsClientService.getTemplateDetail(templateIdOrKey);
      setTemplateDetail(detail);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Failed to load template detail");
    }
  };

  const runRecommendation = async (): Promise<void> => {
    setActionLoading(true);
    setError(null);
    setMessage(null);
    try {
      const payload = await settingsClientService.recommendTemplate();
      setRecommendation(payload);
      setMessage(payload.usedFallback ? `Recommendation generated by fallback: ${payload.fallbackReason ?? "unknown"}` : "Template recommendation ready.");
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Failed to recommend template");
    } finally {
      setActionLoading(false);
    }
  };

  const runPreview = async (): Promise<void> => {
    if (!selectedTemplateIdOrKey) return;
    setActionLoading(true);
    setError(null);
    setMessage(null);
    try {
      const payload = await settingsClientService.previewTemplateApply({
        templateIdOrKey: selectedTemplateIdOrKey,
        applyMode,
        applyStrategy
      });
      setPreview({
        diff: payload.diff,
        summary: payload.summary,
        summaryUsedFallback: payload.summaryUsedFallback,
        summaryFallbackReason: payload.summaryFallbackReason
      });
      setMessage("Template preview generated.");
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Failed to preview template apply");
    } finally {
      setActionLoading(false);
    }
  };

  const runApply = async (): Promise<void> => {
    if (!selectedTemplateIdOrKey || !canWrite) return;
    setActionLoading(true);
    setError(null);
    setMessage(null);
    try {
      const payload = await settingsClientService.applyTemplate({
        templateIdOrKey: selectedTemplateIdOrKey,
        applyMode,
        applyStrategy,
        generateDemoSeed
      });
      setMessage(
        payload.demoSeed.executed
          ? `Template applied. Demo seed: ${payload.demoSeed.summary ?? "done"}`
          : "Template applied successfully."
      );
      await load();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Failed to apply template");
    } finally {
      setActionLoading(false);
    }
  };

  if (loading || !state) {
    return <div className="text-sm text-muted-foreground">Loading template center...</div>;
  }

  return (
    <div>
      <PageHeader
        title="Industry Template Center"
        description="Choose an industry package to accelerate onboarding/demo quality and align pipeline, alerts, prep and playbooks."
        action={
          <div className="flex items-center gap-2">
            <Button variant="outline" onClick={() => void load()} disabled={loading || actionLoading}>
              Refresh
            </Button>
            <Button asChild variant="outline">
              <Link href="/settings/onboarding">Back To Onboarding</Link>
            </Button>
          </div>
        }
      />

      {error ? <p className="mb-3 text-sm text-rose-600">{error}</p> : null}
      {message ? <p className="mb-3 text-sm text-emerald-700">{message}</p> : null}

      <section className="mb-4 grid gap-4 xl:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle>Current Assignment</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <p>role={state.role}</p>
            {state.currentTemplate ? (
              <>
                <p>
                  active template:{" "}
                  <Badge variant="secondary">
                    {state.currentTemplate.displayName} ({state.currentTemplate.templateKey})
                  </Badge>
                </p>
                <p>assignment mode: {state.currentAssignment?.applyMode ?? "-"}</p>
                <p>assignment strategy: {state.currentAssignment?.applyStrategy ?? "-"}</p>
              </>
            ) : (
              <p className="text-muted-foreground">No active template yet.</p>
            )}
            {!canWrite ? <p className="text-xs text-muted-foreground">Read-only: owner/admin required for apply operations.</p> : null}
          </CardContent>
        </Card>

        <Card className="xl:col-span-2">
          <CardHeader>
            <CardTitle>Template Selection</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <Select value={selectedTemplateIdOrKey} onValueChange={(value) => void loadDetail(value)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {state.templates.map((item) => (
                  <SelectItem key={item.id} value={item.id}>
                    {item.displayName} ({item.templateKey})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            <div className="grid gap-3 md:grid-cols-3">
              <div>
                <p className="mb-1 text-xs text-muted-foreground">Apply mode</p>
                <Select value={applyMode} onValueChange={(value) => setApplyMode(value as TemplateApplyMode)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {APPLY_MODES.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <p className="mb-1 text-xs text-muted-foreground">Apply strategy</p>
                <Select value={applyStrategy} onValueChange={(value) => setApplyStrategy(value as TemplateApplyStrategy)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {APPLY_STRATEGIES.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-end">
                <Button
                  variant={generateDemoSeed ? "default" : "outline"}
                  className="w-full"
                  onClick={() => setGenerateDemoSeed((prev) => !prev)}
                >
                  {generateDemoSeed ? "Demo Seed: ON" : "Demo Seed: OFF"}
                </Button>
              </div>
            </div>

            <div className="flex flex-wrap gap-2">
              <Button variant="outline" onClick={() => void runRecommendation()} disabled={actionLoading}>
                Recommend Template
              </Button>
              <Button variant="outline" onClick={() => void runPreview()} disabled={actionLoading || !selectedTemplateIdOrKey}>
                Preview Apply
              </Button>
              <Button onClick={() => void runApply()} disabled={actionLoading || !selectedTemplateIdOrKey || !canWrite}>
                Apply Template
              </Button>
            </div>
          </CardContent>
        </Card>
      </section>

      {recommendation ? (
        <section className="mb-4">
          <Card>
            <CardHeader>
              <CardTitle>Template Fit Recommendation</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <p>
                recommended:{" "}
                <Badge variant="secondary">{recommendation.recommendation.recommendedTemplateKey}</Badge>
              </p>
              <p>apply mode: {recommendation.recommendation.recommendedApplyMode}</p>
              <p>fit reasons: {recommendation.recommendation.fitReasons.join(" / ") || "-"}</p>
              <p>mismatch risks: {recommendation.recommendation.risksOfMismatch.join(" / ") || "-"}</p>
              <p>recommended overrides: {recommendation.recommendation.recommendedOverrides.join(" / ") || "-"}</p>
              {recommendation.usedFallback ? (
                <p className="text-xs text-amber-700">fallback used: {recommendation.fallbackReason ?? "unknown"}</p>
              ) : null}
            </CardContent>
          </Card>
        </section>
      ) : null}

      <section className="mb-4 grid gap-4 xl:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Template Detail</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            {!templateDetail ? <p className="text-muted-foreground">Select a template to view details.</p> : null}
            {templateDetail ? (
              <>
                <p className="text-slate-900 font-semibold">{templateDetail.template.displayName}</p>
                <p className="text-muted-foreground">{templateDetail.template.summary}</p>
                <p>customer stages: {((templateDetail.template.templatePayload.customer_stages as string[] | undefined) ?? []).join(" -> ") || "-"}</p>
                <p>opportunity stages: {((templateDetail.template.templatePayload.opportunity_stages as string[] | undefined) ?? []).join(" -> ") || "-"}</p>
                <p>alert rules: {JSON.stringify(templateDetail.template.templatePayload.default_alert_rules ?? {}, null, 0)}</p>
                <p>checkpoints: {((templateDetail.template.templatePayload.suggested_checkpoints as string[] | undefined) ?? []).join(" / ") || "-"}</p>
                <p>manager signals: {((templateDetail.template.templatePayload.manager_attention_signals as string[] | undefined) ?? []).join(" / ") || "-"}</p>
                <p>demo profile: {String(templateDetail.template.templatePayload.demo_seed_profile ?? "-")}</p>
              </>
            ) : null}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Scenario Packs & Seeded Playbooks</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            {!templateDetail ? <p className="text-muted-foreground">No template selected.</p> : null}
            {templateDetail ? (
              <>
                <p>scenario packs: {templateDetail.scenarioPacks.length}</p>
                <div className="space-y-2">
                  {templateDetail.scenarioPacks.slice(0, 6).map((item) => (
                    <div key={item.id} className="rounded border p-2">
                      <p className="font-medium text-slate-900">{item.title}</p>
                      <p className="text-xs text-muted-foreground">{item.packType}</p>
                      <p className="text-xs text-slate-700">{item.summary}</p>
                    </div>
                  ))}
                </div>
                <p>seeded playbooks: {templateDetail.seededPlaybookTemplates.length}</p>
                <div className="space-y-2">
                  {templateDetail.seededPlaybookTemplates.slice(0, 4).map((item) => (
                    <div key={item.id} className="rounded border p-2">
                      <p className="font-medium text-slate-900">{item.title}</p>
                      <p className="text-xs text-muted-foreground">{item.playbookType}</p>
                      <p className="text-xs text-slate-700">{item.summary}</p>
                    </div>
                  ))}
                </div>
              </>
            ) : null}
          </CardContent>
        </Card>
      </section>

      {preview ? (
        <section>
          <Card>
            <CardHeader>
              <CardTitle>Apply Preview Diff</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <p>changed: {preview.diff.changedKeys.join(", ") || "-"}</p>
              <p>unchanged: {preview.diff.unchangedKeys.join(", ") || "-"}</p>
              <p>notes: {preview.diff.notes.join(" / ") || "-"}</p>
              <p>will change: {preview.summary.whatWillChange.join(" / ") || "-"}</p>
              <p>will not change: {preview.summary.whatWillNotChange.join(" / ") || "-"}</p>
              <p>caution: {preview.summary.cautionNotes.join(" / ") || "-"}</p>
              <p>next steps: {preview.summary.recommendedNextSteps.join(" / ") || "-"}</p>
              {preview.summaryUsedFallback ? (
                <p className="text-xs text-amber-700">summary fallback used: {preview.summaryFallbackReason ?? "unknown"}</p>
              ) : null}
            </CardContent>
          </Card>
        </section>
      ) : null}
    </div>
  );
}
